export { EventSystem } from './events/EventSystem';
export type { SpaceGraphEvents } from './events/EventSystem';
export { PluginManager, type Plugin } from './PluginManager';
export { TypeRegistry } from './TypeRegistry';
export type { NodeConstructor, EdgeConstructor } from './TypeRegistry';
export { CameraControls } from './CameraControls';
export type { CameraControlsConfig } from './CameraControls';
export { ObjectPool, MathPool } from './pooling/ObjectPool';
export { withPooledVector3, withPooledVector2, withPooledMatrix4, withPooledBox3 } from './pooling/ObjectPool';
export { SpatialIndex, BVH } from './spatial/SpatialIndex';
export { SpaceGraph } from '../SpaceGraph';
export type { SpaceGraphOptions } from '../types';
export { Property, type PropertyChange } from './Property';
export { ComputedProperty } from './ComputedProperty';
